base/apps/coin_app/models.py
from timeit import default_timer
from base import db
from sqlalchemy import Column , Integer , String , Boolean , Float , DateTime , ForeignKey
from sqlalchemy.sql import func

class coin(db.Model):
    __tablename__ = 'Coin'
    id = Column(Integer, primary_key=True)
    currency = Column(String(128) , nullable=False)
    name = Column(String(128) , nullable=False)
    fullName = Column(String(128) , nullable=False)
    precision = Column(Integer , nullable=True)
    confirms = Column(Integer , nullable=True)
    contractAddress = Column(String(128) , nullable=True)
    withdrawalMinSize = Column(String(128) , nullable=False)
    withdrawalMinFee = Column(String(128) , nullable=False)
    isWithdrawEnabled = Column(Boolean , nullable=False)
    isDepositEnabled = Column(Boolean , nullable=False)
    isMarginEnabled = Column(Boolean , nullable=False)
    isDebitEnabled = Column(Boolean , nullable=False)
    prices = db.relationship('price' , backref='coin' , lazy=True)

    def __repr__(self) -> str:
        return f'{self.fullName}'
        #return super().__repr__()

class price(db.Model):
    __tablename__ = "Price"
    id = Column(Integer, primary_key=True)
    coin_id = Column(Integer , ForeignKey('Coin.id' , ondelete='cascade'))
    price = Column(Float , nullable=False)
    date = Column(DateTime(timezone=True) , server_default=func.now())

base/__init__.py
from flask import Flask
from base.config import Development
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
# from flask_bcrypt import Bcrypt
# from flask_login import LoginManager
# from flask_mail import Mail

from flask_admin.contrib.sqla import ModelView
from flask_admin import Admin


from celery import Celery
from celery.utils.log import get_task_logger

from flask_socketio import SocketIO

app = Flask(__name__)
app.config.from_object(Development)

#SOCKET
socketio = SocketIO(app)

# #EMAIL
# mail = Mail(app)

#Databese
db = SQLAlchemy(app)
migrate = Migrate(app , db)

# #Bcrypt
# bcrypt = Bcrypt(app)

#CELERY
logger = get_task_logger(__name__)
celery = Celery(app.name)
celery.config_from_object('base.config:Development')
celery.autodiscover_tasks()

# #Loginmanager
# login_manager = LoginManager(app)
# login_manager.login_view = 'users.login'
# login_manager.login_message = 'Please login to access this page!'
# login_manager.login_message_category = 'warning'

#Register Blueprints
from base.apps.coin_app import coins
# from directory.apps.posts_app import posts
# from directory.apps.errors_app import errors

app.register_blueprint(coins)
# app.register_blueprint(posts)
# app.register_blueprint(errors)

#ADMIN
from base.apps.admin_app import admin

base/apps/admin_app/__init__.py
from flask_admin.contrib.sqla import ModelView
from flask_admin import Admin
from base import app , db
#from flask_login import current_user
#from flask import redirect , url_for , request
#add models
from base.apps.coin_app.models import coin , price

admin = Admin(app, name='Flask Coin', template_mode='bootstrap4')

class BaseModelView(ModelView):
    can_create = True
    can_edit = True
    can_delete = True
    can_view_details = True
    page_size = 100

    # def is_accessible(self):
    #     return current_user.is_authenticated and current_user.role == 1

    # def inaccessible_callback(self, name, **kwargs):
    #     # redirect to login page if user doesn't have access
    #     return redirect(url_for('users.login', next=request.url))

class PostModelView(BaseModelView):
    #column_exclude_list = ['content', ]
    column_searchable_list = ['currency', 'name', 'fullName']
    #column_filters = ['date_posted']
    #column_editable_list = ['title',]
    edit_modal = True
    create_modal = False
    #form_excluded_columns = [] #To remove fields from the create and edit form
    can_export = True

class PriceModelView(BaseModelView):
    #column_exclude_list = ['password', ]
    #column_searchable_list = ['username', 'email']
    #column_filters = ['username' , 'email'] 
    #column_editable_list = ['username' , 'active']
    edit_modal = False
    create_modal = False


admin.add_view(PostModelView(coin, db.session))
admin.add_view(PriceModelView(price, db.session))

base/apps/coin_app/__init__.py
from flask import Blueprint

coins = Blueprint('coins' , __name__ , url_prefix='/')

from . import views
from . import models

base/apps/coin_app/views.py
from celery import chain
from base import app , socketio
from flask import request, Response , render_template , jsonify
from . import coins
from base.apps.coin_app.models import coin , price
from .tasks import getCoins , addCoinsToDb , getAllPricesTask , getRealTimePriceTask
import json
from base.apps.coin_app import coins

@socketio.on('connect')
def connect():
    print('Client connected!!!!')

@socketio.on('disconnect')
def disconnect():
    print('client disconnected!!!')

@socketio.on('RealTimePrice')
def handle_realtimeprice(data):
    # Send data to event wich name as coin currency name
    this_coin = coin.query.filter_by(currency=data['currency']).first()
    if this_coin:
        task = getRealTimePriceTask.apply_async((data['currency'],),routing_key='high.coin')
        price , this_time = task.get()
        if task.state == 'SUCCESS':
            socketio.emit(data['currency'] , {'value':price ,'time':this_time})
    else:
        socketio.emit(data['currency'] , {'value':0     ,})

@coins.route('/')
def home():
    coins = coin.query.all()
    return render_template('home.html' , coins=coins)

@coins.route('/price/<string:currency>/')
def getPrice(currency):
    """
        Details Page for every coin
        send coin details & All prices for this coin (in json for create a chart) 
    """
    this_coin = coin.query.filter_by(currency=currency).first_or_404()
    print(this_coin.fullName , this_coin.id)

    data = {str(price.date):price.price for price in this_coin.prices}

    return render_template('price.html' , this_coin=this_coin , data=json.dumps(data))



@coins.route('/getAllCoin' , methods=['POST'])
def getAllCoin():
    task = chain(getCoins.s() , addCoinsToDb.s()).apply_async(routing_key='low.coin')
    result = task.get()
    if task.state == 'SUCCESS':
        return jsonify({"result": result , "task_id":task.id}), 202
    else:
        return jsonify({"error":"Error in Fetch data"}) , 500

@coins.route('/getAllPrices' , methods=['POST'])
def getAllPrices():
    task = getAllPricesTask.apply_async()
    result = task.get()
    if task.state == 'SUCCESS':
        return jsonify({"result": f"{result} updated prices for all coins", "task_id":task.id}), 202
    else:
        return jsonify({"result":"Error in Fetch data", "task_id":task.id}) , 500

base/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Coins</title>
    <link rel="stylesheet" href="{{ url_for('static' , filename='main.css') }}">
</head>
<body>
    <div class="container">
        <h1>Flask Coins</h1>
        <div class="loader"></div> 
        <h6 id="text"></h6>
        <button type="button" onclick="getAllCoins()">getAllCoins</button>
        <button type="button" onclick="getAllPrices()">getAllPrices</button>
        <ul>
            {% for coin in coins %}
            <li><a href="{{ url_for('coins.getPrice' , currency=coin.currency) }}">{{coin.name}}</a></li>
            {% endfor %}
        </ul>
    </div>

    <script>
        textElm = document.querySelector('#text');
        loaderElm = document.querySelector('.loader');
        function getAllPrices(){
            loaderElm.style.display = "block";
            fetch('/getAllPrices', {
                method: 'POST',
                headers: {
                'Content-Type': 'application/json'
                },
                body: JSON.stringify({ all: true }),
            })
            .then(response => response.json())
            .then(data => {
                console.log(data);
                textElm.textContent = data.result;
                loaderElm.style.display = "none";
            });
        };

        function getAllCoins() {
            loaderElm.style.display = "block";
            fetch('/getAllCoin', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({ all: true }),
            })
            .then(response => response.json())
            .then(data => {
                console.log(data);
                textElm.textContent = data.result+'\n'+'Taskid:'+'\n'+ data.task_id;
                loaderElm.style.display = "none";
            });
        }
    </script>
</body>
</html>

base/templates/price.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static' , filename='main.css') }}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <h2>{{ this_coin.fullName }}</h2>
        <h6 class="currencyValue">{{ this_coin.currency }}</h6>
        <h3 class="realtime">Real Time Price is: <span id="realtimeprice">...</span> in <span id="realdate">...</span> </h3>
        <p class="detail">Precision: {{ this_coin.precision}}</p>
        <p class="detail">Confirms: {{ this_coin.confirms}}</p>
        <p class="detail">Contractaddress: {{ this_coin.contractAddress}}</p> 	
        <p class="detail">Withdrawalminsize: {{ this_coin.withdrawalMinSize}}</p>
        <p class="detail">Withdrawalminfee: {{ this_coin.withdrawalMinFee}}</p>
        <!-- {% for price in this_coin.prices %}
            <p>{{ price.price }}</p>
        {% endfor %} -->
        <canvas id="myChart" style="width:100%;max-width:800px"></canvas>
    </div>
</body>

    <script>
        function create_chart(data) {
            var xVal = []
            var yVal = []
            for (var [key,val] of Object.entries(data)) {
                //console.log("Key="+new Date(key));
                xVal.push(new Date(key).toLocaleString());
                //console.log("Value="+val);
                yVal.push(val)
            }
            new Chart("myChart", {
                type: "line",
                data: {
                  labels: xVal,
                  datasets: [{
                    label: 'Price',
                    backgroundColor: "rgba(132, 240, 161, 0.2)",
                    borderColor: "rgba(12, 240, 23 ,0.5)",
                    data: yVal,
                    fill: false,
                  }]
                },
                options:{
                    layout: {
                        padding: 20
                    },
                    scales: {
                        yAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'USD'
                        }
                        }],
                        xAxes: [{
                            scaleLabel: {
                                display: true,
                                labelString: 'TIME'
                            }
                        }]
                    }     
                }
              });
        }
        create_chart({{ data|safe }})

        const this_currency = document.querySelector('h6').innerHTML;
        const realtimeprice = document.querySelector('span#realtimeprice');
        const realdate = document.querySelector('span#realdate');
        //const reqInterval = undefined;

        var socket = io.connect();
        socket.on('connect' , function(msg){
            //socket.emit('RealTimePrice' , {'currency':this_currency })
            const reqInterval = setInterval(sendReq , 5000 , {'currency':this_currency});
        });

        function sendReq(data){
            socket.emit('RealTimePrice' , data)
        }
        //Listen on event with coin real currency name
        socket.on(this_currency , function(msg){
            console.log(msg)
            if(msg.time > realdate.innerHTML){ //check received value newer than old one
                realtimeprice.innerHTML = msg.value;
                realdate.innerHTML = msg.time;
            }
        });

        socket.on('disconnect' , function(msg){
            clearInterval(reqInterval);
        });

    </script>
</html>